# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Daniel B. Goodman"
description: > # this means to ignore newlines until "email:"
   Genome Engineering &middot; Computational Biology &middot; Synthetic Immunology

email: dbgoodman@gmail.com
#blog logo
logo: "/assets/images/dbg_headshot2square.png"
text_logo: "/assets/images/dbg_logo.svg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/skyline_hero_img.jpg"

name: 'Daniel Goodman'
author: 'Daniel Goodman'
author_image: "/assets/images/dbg_headshot2square.png"

paginate:	5

url: "http://dbgoodman.com" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@dbgoodman'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/dbgoodman
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    left: True
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/dbgoodman
    desc:	Fork me on github
    left: True
    share_url:
    share_title:
    share_link:

  - icon: orcid
    url:  http://orcid.org/0000-0003-3759-6883
    desc: Find my work on orcid
    left: True
    ai: True
    share_url:
    share_title:
    share_link:

  - icon: google-scholar
    url:  https://scholar.google.com/citations?user=j_1Z_l4AAAAJ
    desc: Find my work on Google Scholar
    right: True
    ai: True
    share_url:
    share_title:
    share_link:

  - icon: linkedin
    url:  https://www.linkedin.com/in/dbgoodman/
    desc: Add me on linkedin
    right: True
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
